//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataOutputer.ServiceReferenceTurorial {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceTurorial.insert_dataSoap")]
    public interface insert_dataSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        DataOutputer.ServiceReferenceTurorial.HelloWorldResponse HelloWorld(DataOutputer.ServiceReferenceTurorial.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<DataOutputer.ServiceReferenceTurorial.HelloWorldResponse> HelloWorldAsync(DataOutputer.ServiceReferenceTurorial.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name str from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/My_Data", ReplyAction="*")]
        DataOutputer.ServiceReferenceTurorial.My_DataResponse My_Data(DataOutputer.ServiceReferenceTurorial.My_DataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/My_Data", ReplyAction="*")]
        System.Threading.Tasks.Task<DataOutputer.ServiceReferenceTurorial.My_DataResponse> My_DataAsync(DataOutputer.ServiceReferenceTurorial.My_DataRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public DataOutputer.ServiceReferenceTurorial.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(DataOutputer.ServiceReferenceTurorial.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public DataOutputer.ServiceReferenceTurorial.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(DataOutputer.ServiceReferenceTurorial.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class My_DataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="My_Data", Namespace="http://tempuri.org/", Order=0)]
        public DataOutputer.ServiceReferenceTurorial.My_DataRequestBody Body;
        
        public My_DataRequest() {
        }
        
        public My_DataRequest(DataOutputer.ServiceReferenceTurorial.My_DataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class My_DataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str;
        
        public My_DataRequestBody() {
        }
        
        public My_DataRequestBody(string str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class My_DataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="My_DataResponse", Namespace="http://tempuri.org/", Order=0)]
        public DataOutputer.ServiceReferenceTurorial.My_DataResponseBody Body;
        
        public My_DataResponse() {
        }
        
        public My_DataResponse(DataOutputer.ServiceReferenceTurorial.My_DataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class My_DataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string My_DataResult;
        
        public My_DataResponseBody() {
        }
        
        public My_DataResponseBody(string My_DataResult) {
            this.My_DataResult = My_DataResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface insert_dataSoapChannel : DataOutputer.ServiceReferenceTurorial.insert_dataSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class insert_dataSoapClient : System.ServiceModel.ClientBase<DataOutputer.ServiceReferenceTurorial.insert_dataSoap>, DataOutputer.ServiceReferenceTurorial.insert_dataSoap {
        
        public insert_dataSoapClient() {
        }
        
        public insert_dataSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public insert_dataSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public insert_dataSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public insert_dataSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataOutputer.ServiceReferenceTurorial.HelloWorldResponse DataOutputer.ServiceReferenceTurorial.insert_dataSoap.HelloWorld(DataOutputer.ServiceReferenceTurorial.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            DataOutputer.ServiceReferenceTurorial.HelloWorldRequest inValue = new DataOutputer.ServiceReferenceTurorial.HelloWorldRequest();
            inValue.Body = new DataOutputer.ServiceReferenceTurorial.HelloWorldRequestBody();
            DataOutputer.ServiceReferenceTurorial.HelloWorldResponse retVal = ((DataOutputer.ServiceReferenceTurorial.insert_dataSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataOutputer.ServiceReferenceTurorial.HelloWorldResponse> DataOutputer.ServiceReferenceTurorial.insert_dataSoap.HelloWorldAsync(DataOutputer.ServiceReferenceTurorial.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataOutputer.ServiceReferenceTurorial.HelloWorldResponse> HelloWorldAsync() {
            DataOutputer.ServiceReferenceTurorial.HelloWorldRequest inValue = new DataOutputer.ServiceReferenceTurorial.HelloWorldRequest();
            inValue.Body = new DataOutputer.ServiceReferenceTurorial.HelloWorldRequestBody();
            return ((DataOutputer.ServiceReferenceTurorial.insert_dataSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataOutputer.ServiceReferenceTurorial.My_DataResponse DataOutputer.ServiceReferenceTurorial.insert_dataSoap.My_Data(DataOutputer.ServiceReferenceTurorial.My_DataRequest request) {
            return base.Channel.My_Data(request);
        }
        
        public string My_Data(string str) {
            DataOutputer.ServiceReferenceTurorial.My_DataRequest inValue = new DataOutputer.ServiceReferenceTurorial.My_DataRequest();
            inValue.Body = new DataOutputer.ServiceReferenceTurorial.My_DataRequestBody();
            inValue.Body.str = str;
            DataOutputer.ServiceReferenceTurorial.My_DataResponse retVal = ((DataOutputer.ServiceReferenceTurorial.insert_dataSoap)(this)).My_Data(inValue);
            return retVal.Body.My_DataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataOutputer.ServiceReferenceTurorial.My_DataResponse> DataOutputer.ServiceReferenceTurorial.insert_dataSoap.My_DataAsync(DataOutputer.ServiceReferenceTurorial.My_DataRequest request) {
            return base.Channel.My_DataAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataOutputer.ServiceReferenceTurorial.My_DataResponse> My_DataAsync(string str) {
            DataOutputer.ServiceReferenceTurorial.My_DataRequest inValue = new DataOutputer.ServiceReferenceTurorial.My_DataRequest();
            inValue.Body = new DataOutputer.ServiceReferenceTurorial.My_DataRequestBody();
            inValue.Body.str = str;
            return ((DataOutputer.ServiceReferenceTurorial.insert_dataSoap)(this)).My_DataAsync(inValue);
        }
    }
}
